# Project: BLITZGECKO
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = dictree.o functions.o common.o
LINKOBJ  = dictree.o functions.o common.o
LIBS     = -L"E:/Programas/Dev-CppTDM/MinGW64/lib" -L"E:/Programas/Dev-CppTDM/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Programas/Dev-CppTDM/MinGW64/include" -I"E:/Programas/Dev-CppTDM/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programas/Dev-CppTDM/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Programas/Dev-CppTDM/MinGW64/include" -I"E:/Programas/Dev-CppTDM/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programas/Dev-CppTDM/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Programas/Dev-CppTDM/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = BLITZGECKO.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

dictree.o: dictree.c
	$(CC) -c dictree.c -o dictree.o $(CFLAGS)

functions.o: functions.c
	$(CC) -c functions.c -o functions.o $(CFLAGS)

common.o: common.c
	$(CC) -c common.c -o common.o $(CFLAGS)
